# Generated by Django 4.1.1 on 2023-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_postindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('ticket_url', models.URLField(blank=True)),
            ],
        ),
    ]
