# Generated by Django 4.1.1 on 2023-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='postindex',
            name='post_index_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
