# Generated by Django 4.1.1 on 2023-03-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_alter_postindex_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postindex',
            name='status',
        ),
    ]
