# Generated by Django 4.1.1 on 2023-03-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_remove_postindex_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='postindex',
            name='date_event',
            field=models.DateField(null=True),
        ),
    ]
