# Generated by Django 4.1.1 on 2023-03-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_postindex_date_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postindex',
            name='date_event',
        ),
    ]
