# Generated by Django 4.1.1 on 2023-03-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_remove_postindex_date_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
