# Generated by Django 4.1.1 on 2023-03-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0010_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link_urkl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
