# Generated by Django 4.1.1 on 2023-03-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0011_event_link_status_event_link_urkl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Subkategoria'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Wydarzenie', 'verbose_name_plural': 'Wydarzenia'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Posty w Kategoriach', 'verbose_name_plural': 'Post w Kategorii'},
        ),
        migrations.AlterModelOptions(
            name='postindex',
            options={'verbose_name': 'Posy na Stronie Głównej', 'verbose_name_plural': 'Post na Stronie Głównej'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subkategorie', 'verbose_name_plural': 'Subkategoria'},
        ),
    ]
