# Generated by Django 4.1.1 on 2023-03-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0012_alter_category_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategoria'},
        ),
    ]
